### ISSUE TITLE
profiles loosing names

### ISSUE THREAD

**Issue by Dinala** [Cimbali/swap-cookies#1]
When I close firefox and relaunch it, the profile loose the names that I give them.
![image](https://user-images.githubusercontent.com/917365/36360057-84339778-14d5-11e8-8764-dce1a1c27931.png)

I'm using Firefox Quantum 58.0.2 on Windows 7

**Comment by Cimbali** [comment]
Yup it's fixed now, version 1.1 is available for download on AMO. Thanks for reporting the bug!
