### ISSUE TITLE
Won't hold cookies

### ISSUE THREAD

**Issue by Dinala** [Cimbali/swap-cookies#2]
I tend to leave Firefox open for several days. I'll have the different accounts all signed in and 

working. When I leave Firefox idle for hours, the profiles 1 & 3-13 are now signed in as the account 13. The second profile is fine. If I go back to the first profile to sign out and sign back in as account 1 and then try to sign into profile 3 as account 3, all but profile 2 change to account 3.

If I relaunch Firefox and try to log into the accounts, it will hold the first account correctly on 

profile 1, but when I sign into account 3 on profile 3, the profiles 3-13 will be logged in as that 

account. When I go to profile 4 and try to log into account 4, profiles 3-13 are now account 4.

I either have to delete and reset up all the profiles or relaunch Firefox after logging into each account on each profile.

Profile 2 seems to always be correct.

Firefox 58.0.2
Windows 7
Swap Cookies 1.1

**Comment by Dinala** [comment]
I just tried this using only 3 profiles and it still happened.

And after closing Firefox when I went to bed, all the profiles were logged in as account 3 when I launched it in the morning.

**Comment by Cimbali** [comment]
Hi @Dinala, I can't seem to reproduce this. Which website are you using? Do you have other plugins that might interfere?

Cookies are saved and loaded whenever you click the swap button, nothing else happens at any other time, so that's when something goes wrong, either storing or loading cookies.
Were all 3 accounts (and switching between them) working fine before you switched off firefox?

**Comment by Dinala** [comment]
I'm using it for gaiaonline.com
The only other plugins that were enabled were Adblock Plus, GaiaUpgrade, and Snap Links.

I tried it with all other plugins disabled and let Firefox sit idle. Profiles 1 & 3 were now logged in as account 3. Profile 2 stayed correct.

Yes, all 3 accounts were working when I closed Firefox last time.

**Comment by Cimbali** [comment]
I'm guessing something went wrong during the upgrade, some stored set of cookies must be invalid and prohibit saving/loading the others properly. Can you try removing all the profiles for the website to purge the storage, and adding them again?

**Comment by Dinala** [comment]
Still happens.
I upgraded to 1.2
I also removed the plugin, restarted my computer and added it back and it still did it.

**Comment by Dinala** [comment]
I tried it with another site and it worked for that site but not for gaiaonline.

**Comment by Cimbali** [comment]
Do you maybe use different subdomains on gaiaonline? `www.gaiaonline.com` sometimes, directly `gaiaonline.com` some other times, or  `<something_else>.gaiaonline.com`?

**Comment by Dinala** [comment]
no. its always https://www.gaiaonline.com
If I try to go to gaiaonline.com it auto turns into https://www.gaiaonline.com

I just went and looked at the cookies and it does say the domain is for gaiaonline.com

**Comment by Dinala** [comment]
I think that it grabs the last batch of cookies made for that site. When I made 2 profiles it signed profile 1 in as account 2 after being idle.

**Comment by Cimbali** [comment]
Alright I figured it out. Turns out that even though you only use `www.gaiaonline.com`, the cookies are set for `gaiaonline.com`, so when we don't catch all cookies by filtering by URL. That means we need to detect the proper scope for cookie saving/restoring and use it (in this case `*.gaiaonline.com`).

**Comment by Cimbali** [comment]
The update is online on AMO @Dinala, can you tell me whether it works for you? I tested and you should be all right.

**Comment by Dinala** [comment]
Yes it is working now. Thank you very much.
