### ISSUE TITLE
Feature request: display the currently selected profile witout having to click on the extension icon

### ISSUE THREAD

**Issue by syldub69** [Cimbali/swap-cookies#4]
I don't know how you could do this, but could you give an indication in Firefox to display which is the currently selected Cookie profile? (without having to click on the extension icon).
I know that in Firefox Quantum a lot of thing is locked.
Maybe you can display something in the Windows title, or in the status bar... ?

**Comment by Cimbali** [comment]
Hovering the icon isn't a big improvement I guess? I can write over the icon I think, but there's probably only room for 4-5 characters. There's no real statusbar anymore, and modifying the page is kind of hard too.

**Comment by Cimbali** [comment]
Yeah just checked and badges seem to cut out at 4 characters.

**Comment by Cimbali** [comment]
We can colour-code as well. *4 chars + colour* should be good enough.

**Comment by syldub69** [comment]
Yes, that would be better than nothing!
Hover will require a mouse move, but it will still save a click :o)

**Comment by syldub69** [comment]
I found an example of an addon which change its icon in toolbar depending of the addon state:
https://addons.mozilla.org/en-US/firefox/addon/tab-auto-refresh/
Maybe you could implement the same. For instance, you could add a little colored square on the corner of the CookieSwap icon, and let manage the color with options (or hardcode them if too difficult to do)

**Comment by Cimbali** [comment]
I added this preview feature without colour coding, I can always add that later if it is necessary. For now we display the 4 first characters of the loaded profile in the badge (i.e. on top of the icon).

It's available on AMO in v1.2 now.

**Comment by syldub69** [comment]
Really nice! Color coding is not necessary I think.
It can even display 5 characters! (try: "Sylvain")
